name: CI/CD

on:
  push:
    branches: [ main, .* ]
  pull_request:
    branches: [ main, .* ]

  workflow_dispatch:

jobs:
  CodeStyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Codestyle
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install flake8
          python3 -m flake8 ./ --ignore=F401,E402
  
  Tests:
    runs-on: ubuntu-latest
    needs: CodeStyle
    steps:
      - uses: actions/checkout@v2
      - name: Check tests
        run: |
          sudo apt update
          sudo apt install python3-pip -y
          pip3 install -e '.[test]'
          python3 -m coverage run -m pytest
          python3 -m coverage report
